### ISSUE TITLE
Can't access settings pane on Linux

### ISSUE THREAD

**Issue by conruggles** [wexond/browser-base#108]
### Expected behavior
I would expect that you can access the settings pane when you click on 'Settings' in the context menu, but it produces the exception in the terminal pasted below.

### Actual behavior
Just get a console error and a stack trace.

### Steps to reproduce the problem
Open up the browser, go to context menu, click on settings, get this stack trace in the terminal:
```
Checking for update
Error: Error: ENOENT: no such file or directory, open '/opt/Wexond/resources/app-update.yml'
    at /opt/Wexond/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:391:27
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.loadUpdateConfig (/opt/Wexond/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:555:7)
    at Lazy.AppUpdater.configOnDisk (/opt/Wexond/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:134:43)
    at Lazy.get value [as value] (/opt/Wexond/resources/app.asar/node_modules/lazy-val/src/main.ts:18:23)
    at /opt/Wexond/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:298:46
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at AppImageUpdater.getUpdateInfo (/opt/Wexond/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:460:7)
    at /opt/Wexond/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:308:35
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.doCheckForUpdates (/opt/Wexond/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:502:7)
    at /opt/Wexond/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:279:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at AppImageUpdater._checkForUpdates (/opt/Wexond/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:433:7)
    at AppImageUpdater.checkForUpdates (/opt/Wexond/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:217:35)
    at EventEmitter.ipcMain.on.e (/opt/Wexond/resources/app.asar/src/main/index.js:119:15)
    at emitOne (events.js:116:13)
    at EventEmitter.emit (events.js:211:7)
    at WebContents.<anonymous> (/opt/Wexond/resources/electron.asar/browser/api/web-contents.js:286:13)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)
```

### Specifications
* Version: 1.0.0-beta.1
* OS: elementary OS 0.4.1

**Comment by sentialx** [comment]
Thanks for your issue. The settings pane is not implemented yet. The logs are related to the auto updater.
