### ISSUE TITLE
Program doesn't create its folder and .config files

### ISSUE THREAD

**Issue by pzmarzly** [wexond/browser-base#116]
I tried running

```text
npm run watch
npm start
```

On first attempt, npm start resulted in:

```text
A JavaScript error occurred in the main process
Uncaught Exception:
Error: ENOENT: no such file or directory, mkdir '/home/pzmarzly/.wexond/plugins'
    at fs.mkdirSync (fs.js:885:18)
    at eval (webpack-internal:///./src/main/index.ts:31:57)
    at Module../src/main/index.ts (/home/pzmarzly/wexond/main.js:2082:1)
    at __webpack_require__ (/home/pzmarzly/wexond/main.js:20:30)
    at /home/pzmarzly/wexond/main.js:84:18
    at Object.<anonymous> (/home/pzmarzly/wexond/main.js:87:10)
    at Object.<anonymous> (/home/pzmarzly/wexond/main.js:2331:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
```

(probably mkdir being non-recursive). But the directories were created, and every next attempt ended with:

![screenshot from 2018-08-12 16-26-34](https://user-images.githubusercontent.com/8074163/44003047-9c28607e-9e4c-11e8-8adb-539029a77d97.png)

A JavaScript error occurred in the main process
Uncaught Exception:
Error: ENOENT: no such file or directory, open '/home/$USER/.config/wexond/window-data.json'

OS: Manjaro + Cinnamon DE

**Comment by sentialx** [comment]
Thanks for your issue! Of course I will check that out, and fix as fast as possible.
