### ISSUE TITLE
npm install  error

### ISSUE THREAD

**Issue by fulus06** [wexond/browser-base#183]
686 verbose stack Error: wexond@2.0.0-beta.11 postinstall: `electron-builder install-app-deps`
686 verbose stack Exit status 1
686 verbose stack     at EventEmitter.<anonymous> (D:\Program Files\nodejs\node_global\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
686 verbose stack     at EventEmitter.emit (events.js:189:13)
686 verbose stack     at ChildProcess.<anonymous> (D:\Program Files\nodejs\node_global\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
686 verbose stack     at ChildProcess.emit (events.js:189:13)
686 verbose stack     at maybeClose (internal/child_process.js:970:16)
686 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
687 verbose pkgid wexond@2.0.0-beta.11
688 verbose cwd H:\Tools\repository\svn\fulusco\wexond
689 verbose Windows_NT 10.0.17763
690 verbose argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_global\\node_modules\\npm\\bin\\npm-cli.js" "install"
691 verbose node v10.15.3
692 verbose npm  v6.4.1
693 error code ELIFECYCLE
694 error errno 1
695 error wexond@2.0.0-beta.11 postinstall: `electron-builder install-app-deps`
695 error Exit status 1
696 error Failed at the wexond@2.0.0-beta.11 postinstall script.
696 error This is probably not a problem with npm. There is likely additional logging output above.
697 verbose exit [ 1, true ]
[2019-04-23T12_59_25_903Z-debug.log](https://github.com/wexond/wexond/files/3107613/2019-04-23T12_59_25_903Z-debug.log)

**Comment by fulus06** [comment]
Error: d:\nodejs\node.exe exited with code 1
Error output:
× Install fail! Error: EEXIST: file already exists, symlink 'H:\Tools\repository\svn\fulusco\wexond\node_modules\_ref@1.3.5@ref' -> 'H:\Tools\repository\svn\fulusco\wexond\node_modules\ref'
Error: EEXIST: file already exists, symlink 'H:\Tools\repository\svn\fulusco\wexond\node_modules\_ref@1.3.5@ref' -> 'H:\Tools\repository\svn\fulusco\wexond\node_modules\ref'
npminstall version: 3.20.2
npminstall args: d:\nodejs\node.exe D:\Program Files\nodejs\node_global\node_modules\cnpm\node_modules\npminstall\bin\install.js rebuild extract-file-icon@0.1.4 ffi@2.3.0 ref@1.3.5 ref@1.3.5 iconv@2.3.4 leveldown@5.0.1 mouse-hooks@0.2.1 ffi@2.3.0 ref@1.3.5 ref@1.3.5 ref@1.3.5 ref@1.3.5 iconv@2.3.4 ref@1.3.5 ref@1.3.5 iconv@2.3.4 ref@1.3.5 ref@1.3.5

    at ChildProcess.childProcess.once.code (H:\Tools\repository\svn\fulusco\wexond\node_modules\_builder-util@9.7.0@builder-util\src\util.ts:244:14)
    at Object.onceWrapper (events.js:272:13)
    at ChildProcess.emit (events.js:180:13)
    at maybeClose (internal/child_process.js:936:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
From previous event:
    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (H:\Tools\repository\svn\fulusco\wexond\node_modules\_bluebird@3.5.4@bluebird\js\release\debuggability.js:411:19)
    at new PromiseSpawn (H:\Tools\repository\svn\fulusco\wexond\node_modules\_bluebird@3.5.4@bluebird\js\release\generators.js:43:17)
    at H:\Tools\repository\svn\fulusco\wexond\node_modules\_bluebird@3.5.4@bluebird\js\release\generators.js:197:21
    at _installAppDeps (H:\Tools\repository\svn\fulusco\wexond\node_modules\_electron-builder@20.39.0@electron-builder\out\cli\install-app-deps.js:176:26)
    at installAppDeps (H:\Tools\repository\svn\fulusco\wexond\node_modules\_electron-builder@20.39.0@electron-builder\out\cli\install-app-deps.js:144:26)
    at then (H:\Tools\repository\svn\fulusco\wexond\node_modules\_electron-builder@20.39.0@electron-builder\src\cli\cli.ts:46:19)
    at <anonymous>
[npminstall:runscript:error] wexond@2.0.0-beta.11 scripts.postinstall run "electron-builder install-app-deps" error: Error: Run "C:\WINDOWS\system32\cmd.exe /d /s /c electron-builder install-app-deps" error, exit code 1
× Install fail! Error: post install error, please remove node_modules before retry!
Run "C:\WINDOWS\system32\cmd.exe /d /s /c electron-builder install-app-deps" error, exit code 1
Error: post install error, please remove node_modules before retry!
Run "C:\WINDOWS\system32\cmd.exe /d /s /c electron-builder install-app-deps" error, exit code 1
    at ChildProcess.proc.on.code (D:\Program Files\nodejs\node_global\node_modules\cnpm\node_modules\runscript\index.js:74:21)
    at ChildProcess.emit (events.js:180:13)
    at maybeClose (internal/child_process.js:936:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)

**Comment by fulus06** [comment]
Configuring yargs through package.json is deprecated and will be removed in the next major release, please use the JS API instead.
  • electron-builder version=20.39.0
  • loaded configuration file=H:\Tools\repository\svn\fulusco\wexond-master\electron-builder.json
  • rebuilding native production dependencies platform=win32 arch=x64
Error: d:\nodejs\node.exe exited with code 1
Error output:
× Install fail! Error: EEXIST: file already exists, symlink 'H:\Tools\repository\svn\fulusco\wexond-master\node_modules\_ffi@2.3.0@ffi' -> 'H:\Tools\repository\svn\fu lusco\wexond-master\node_modules\ffi'
Error: EEXIST: file already exists, symlink 'H:\Tools\repository\svn\fulusco\wexond-master\node_modules\_ffi@2.3.0@ffi' -> 'H:\Tools\repository\svn\fulusco\wexond-master\node_modules\ffi'
npminstall version: 3.20.2
npminstall args: d:\nodejs\node.exe D:\Program Files\nodejs\node_global\node_modules\cnpm\node_modules\npminstall\bin\install.js rebuild extract-file-icon@0.1.4 ffi@2.3.0 ref@1.3.5 ref@1.3.5 iconv@2.3.4 leveldown@5.0.1 mouse-hooks@0.2.1 ffi@2.3.0 ref@1.3.5 ref@1.3.5 ref@1.3.5 ref@1.3.5 iconv@2.3.4 ref@1.3.5 ref@1.3.5 iconv@2.3.4 ref@1.3.5 ref@1.3.5

    at ChildProcess.childProcess.once.code (H:\Tools\repository\svn\fulusco\wexond-master\node_modules\_builder-util@9.7.0@builder-util\src\util.ts:244:14)
    at Object.onceWrapper (events.js:285:13)
    at ChildProcess.emit (events.js:197:13)
    at maybeClose (internal/child_process.js:984:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
From previous event:
    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (H:\Tools\repository\svn\fulusco\wexond-master\node_modules\_bluebird@3.5.4@bluebird\js\release\debuggability.js:411:19)
    at new PromiseSpawn (H:\Tools\repository\svn\fulusco\wexond-master\node_modules\_bluebird@3.5.4@bluebird\js\release\generators.js:43:17)
    at H:\Tools\repository\svn\fulusco\wexond-master\node_modules\_bluebird@3.5.4@bluebird\js\release\generators.js:197:21
    at _installAppDeps (H:\Tools\repository\svn\fulusco\wexond-master\node_modules\_electron-builder@20.39.0@electron-builder\out\cli\install-app-deps.js:176:26)
    at installAppDeps (H:\Tools\repository\svn\fulusco\wexond-master\node_modules\_electron-builder@20.39.0@electron-builder\out\cli\install-app-deps.js:144:26)
    at then (H:\Tools\repository\svn\fulusco\wexond-master\node_modules\_electron-builder@20.39.0@electron-builder\src\cli\cli.ts:46:19)
[npminstall:runscript:error] wexond@2.0.0-beta.11 scripts.postinstall run "electron-builder install-app-deps" error: Error: Run "C:\WINDOWS\system32\cmd.exe /d /s /c electron-builder install-app-deps" error, exit code 1
× Install fail! Error: post install error, please remove node_modules before retry!
Run "C:\WINDOWS\system32\cmd.exe /d /s /c electron-builder install-app-deps" error, exit code 1
Error: post install error, please remove node_modules before retry!
Run "C:\WINDOWS\system32\cmd.exe /d /s /c electron-builder install-app-deps" error, exit code 1
    at ChildProcess.proc.on.code (D:\Program Files\nodejs\node_global\node_modules\cnpm\node_modules\runscript\index.js:74:21)
    at ChildProcess.emit (events.js:197:13)
    at maybeClose (internal/child_process.js:984:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)

**Comment by fulus06** [comment]
### Has run successfully, but I don't know how to solve it.
