### ISSUE TITLE
Adblocker cannot fetch resources

### ISSUE THREAD

**Issue by BlobCodes** [wexond/browser-base#383]
**Bug description**
The adblocker doesn't work because it can't fetch its resources.
This can be seen when opening Wexond in the command line, where this error can be seen:
```
(node:31082) UnhandledPromiseRejectionWarning: FetchError: request to https://cdn.cliqz.com/adblocker/resources/ublock-resources/metadata.json failed, reason: self signed certificate in certificate chain
    at ClientRequest.<anonymous> (/tmp/.mount_Wexond1UHHrr/resources/app.asar/build/main.bundle.js:10:326823)
    at ClientRequest.emit (events.js:210:5)
    at TLSSocket.socketErrorListener (_http_client.js:406:9)
    at TLSSocket.emit (events.js:210:5)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(node:31082) UnhandledPromiseRejectionWarning: FetchError: request to https://cdn.cliqz.com/adblocker/resources/ublock-resources/metadata.json failed, reason: self signed certificate in certificate chain
    at ClientRequest.<anonymous> (/tmp/.mount_Wexond1UHHrr/resources/app.asar/build/main.bundle.js:10:326823)
    at ClientRequest.emit (events.js:210:5)
    at TLSSocket.socketErrorListener (_http_client.js:406:9)
    at TLSSocket.emit (events.js:210:5)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

[...]

(node:31082) UnhandledPromiseRejectionWarning: FetchError: request to https://cdn.cliqz.com/adblocker/resources/ublock-resources/metadata.json failed, reason: self signed certificate in certificate chain
    at ClientRequest.<anonymous> (/tmp/.mount_Wexond1UHHrr/resources/app.asar/build/main.bundle.js:10:326823)
    at ClientRequest.emit (events.js:210:5)
    at TLSSocket.socketErrorListener (_http_client.js:406:9)
    at TLSSocket.emit (events.js:210:5)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(node:31082) UnhandledPromiseRejectionWarning: FetchError: request to https://cdn.cliqz.com/adblocker/resources/ublock-resources/metadata.json failed, reason: self signed certificate in certificate chain
    at ClientRequest.<anonymous> (/tmp/.mount_Wexond1UHHrr/resources/app.asar/build/main.bundle.js:10:326823)
    at ClientRequest.emit (events.js:210:5)
    at TLSSocket.socketErrorListener (_http_client.js:406:9)
    at TLSSocket.emit (events.js:210:5)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)


[...]

failed downloading pre-built, fallback to fetching lists
failed downloading pre-built, fallback to fetching lists
failed downloading pre-built, fallback to fetching lists
failed downloading pre-built, fallback to fetching lists
failed downloading pre-built, fallback to fetching lists
failed downloading pre-built, fallback to fetching lists
failed downloading pre-built, fallback to fetching lists
failed downloading pre-built, fallback to fetching lists
failed downloading pre-built, fallback to fetching lists
failed downloading pre-built, fallback to fetching lists
```

**To Reproduce**
1. Remove Wexond's data directory.
2. Open Wexond in command line

**Expected behavior**
The adblocker fetches it's lists and works as expected.

**Screenshots**
None.

**Details:**
 - Operating System: Manjaro Linux
 - Wexond version: 4.0.0-beta.2
 - Last known working Wexond version: Nightly 16

**Additional context**
None.

**Comment by BlobCodes** [comment]
Turns out my system-wide adblocker blocked cdn.cliqz.com.
Not a Wexond issue..

**Comment by sentialx** [comment]
Anyway, Wexond should download the lists directly rather than from cdn.cliqz.com
