### ISSUE TITLE
Version 5beta1 hang up due to CPU consumption

### ISSUE THREAD

**Issue by phucpnt** [wexond/browser-base#455]
**Bug description**
Version 5beta1 hang up and CPU hogging

**To Reproduce**
Fetch the latest source. Checkout to branch v5.0.0-beta.1.
Build the project.
Run dev

**Expected behavior**
Run dev and see the new tab page

**Screenshots**
<img width="912" alt="Screen Shot 2020-05-01 at 9 38 06 AM" src="https://user-images.githubusercontent.com/378993/80779246-4ad3bd80-8b95-11ea-959b-17116403e112.png">

**Details:**
 - Operating System: MacOS
 - Wexond version: 5.0.0-beta.1
 - Last known working Wexond version: 4.0.0-beta-4

**Additional context**
Console output in dev running
```
[1] Error occurred in handler for 'view-select-1': TypeError: Cannot read property 'hide' of undefined
[1]     at ViewManager.select (/Users/phucpnt/projects/invest/packages/invest-browser/build/webpack:/src/main/view-manager.ts:172:39)
[1]     at u.<anonymous> (/Users/phucpnt/projects/invest/packages/invest-browser/build/webpack:/src/main/windows-service.ts:14:23)
[1]     at u.emit (events.js:223:5)
[1]     at u.activate (/Users/phucpnt/projects/invest/packages/invest-browser/build/webpack:/node_modules/electron-extensions/build/index.js:1:10730)
[1]     at /Users/phucpnt/projects/invest/packages/invest-browser/build/webpack:/src/main/view-manager.ts:56:23
[1]     at electron/js2c/browser_init.js:6087:52
[1]     at WebContents.<anonymous> (electron/js2c/browser_init.js:4015:42)
[1]     at WebContents.emit (events.js:223:5)
[1] Update for version 5.0.0-nightly.12 is not available (latest version: 5.0.0-beta.1, downgrade is disallowed).
```

Cheers

**Comment by phucpnt** [comment]
@sentialx anything I can help to fix this bug. Any clue to start debugging?

**Comment by sentialx** [comment]
@phucpnt I doubt it's easily debuggable. I'm removing temporarily parts in the code and see what causes performance problems. I suspect it's a problem with loading BrowserViews for each dialog simultaneously. I'm working on this in `dialogs-recycling` branch.

**Comment by sentialx** [comment]
@phucpnt Is this issue still relevant on [Wexond 5.0.0-nightly.15](https://github.com/wexond/desktop-nightly/releases/tag/v5.0.0-nightly.15)?

**Comment by phucpnt** [comment]
Thanks @sentialx  Let me check on my machine

**Comment by phucpnt** [comment]
@sentialx it seems having some improvements. But still the issue occurs and hogging the CPU
<img width="912" alt="Screen Shot 2020-05-04 at 10 29 30 PM" src="https://user-images.githubusercontent.com/378993/80983774-29095d80-8e57-11ea-826d-c5a239612c9c.png">

I suspect some weird behavior on the location input bar. When I type in the response is super getting stuck

When I run build from the master and run `dev`. The console looping output the following

```
[1] TypeError: Object has been destroyed
[1]     at /Users/phucpnt/projects/wexond/build/webpack:/src/main/services/dialogs-service.ts:136:45
[1]     at Array.forEach (<anonymous>)
[1]     at DialogsService.sendToAll (/Users/phucpnt/projects/wexond/build/webpack:/src/main/services/dialogs-service.ts:136:28)
[1]     at Settings.update (/Users/phucpnt/projects/wexond/build/webpack:/src/main/models/settings.ts:87:34)
[1]     at NativeTheme.<anonymous> (/Users/phucpnt/projects/wexond/build/webpack:/src/main/models/settings.ts:57:12)
[1]     at NativeTheme.emit (events.js:223:5)
[1] TypeError: Object has been destroyed
[1]     at /Users/phucpnt/projects/wexond/build/webpack:/src/main/services/dialogs-service.ts:136:45
[1]     at Array.forEach (<anonymous>)
[1]     at DialogsService.sendToAll (/Users/phucpnt/projects/wexond/build/webpack:/src/main/services/dialogs-service.ts:136:28)
[1]     at Settings.update (/Users/phucpnt/projects/wexond/build/webpack:/src/main/models/settings.ts:87:34)
[1]     at NativeTheme.<anonymous> (/Users/phucpnt/projects/wexond/build/webpack:/src/main/models/settings.ts:57:12)
[1]     at NativeTheme.emit (events.js:223:5)
[1] TypeError: Object has been destroyed
[1]     at /Users/phucpnt/projects/wexond/build/webpack:/src/main/services/dialogs-service.ts:136:45
[1]     at Array.forEach (<anonymous>)
[1]     at DialogsService.sendToAll (/Users/phucpnt/projects/wexond/build/webpack:/src/main/services/dialogs-service.ts:136:28)
[1]     at Settings.update (/Users/phucpnt/projects/wexond/build/webpack:/src/main/models/settings.ts:87:34)
[1]     at NativeTheme.<anonymous> (/Users/phucpnt/projects/wexond/build/webpack:/src/main/models/settings.ts:57:12)
``

**Comment by sentialx** [comment]
How can I reproduce these errors?

**Comment by phucpnt** [comment]
From my side, I do the following:
* Get the code from master (wexond/desktop)
* `yarn install`
* `yarn rebuild`
* `yarn dev`

You can check the screenshot as below for performance monitor in devtools:
<img width="912" alt="Screen Shot 2020-05-04 at 10 55 01 PM" src="https://user-images.githubusercontent.com/378993/80986260-87840b00-8e5a-11ea-8b34-8adf4d2e7a6e.png">

Also there are some error in the console
```
[1] ERROR in /Users/phucpnt/projects/wexond/src/main/application.ts(66,40):
[1] TS2339: Property 'dialogs' does not exist on type 'AppWindow'.
[1] ERROR in /Users/phucpnt/projects/wexond/src/main/dialogs/auth.ts(8,24):
[1] TS2307: Cannot find module '.'.
[1] ERROR in /Users/phucpnt/projects/wexond/src/main/dialogs/auth.ts(30,12):
[1] TS2339: Property 'show' does not exist on type 'AuthDialog'.
[1] ERROR in /Users/phucpnt/projects/wexond/src/main/dialogs/auth.ts(31,12):
[1] TS2339: Property 'tabIds' does not exist on type 'AuthDialog'.
[1] ERROR in /Users/phucpnt/projects/wexond/src/main/dialogs/auth.ts(33,12):
[1] TS2339: Property 'send' does not exist on type 'AuthDialog'.
[1] ERROR in /Users/phucpnt/projects/wexond/src/main/dialogs/auth.ts(35,48):
[1] TS2339: Property 'appWindow' does not exist on type 'AuthDialog'.
[1] ERROR in /Users/phucpnt/projects/wexond/src/main/dialogs/auth.ts(36,14):
[1] TS2339: Property 'tabIds' does not exist on type 'AuthDialog'.
[1] ERROR in /Users/phucpnt/projects/wexond/src/main/dialogs/auth.ts(36,28):
[1] TS2339: Property 'tabIds' does not exist on type 'AuthDialog'.
[1] ERROR in /Users/phucpnt/projects/wexond/src/main/dialogs/auth.ts(36,43):
[1] TS7006: Parameter 'x' implicitly has an 'any' type.
[1] ERROR in /Users/phucpnt/projects/wexond/src/main/dialogs/auth.ts(37,14):
[1] TS2339: Property 'hide' does not exist on type 'AuthDialog'.
[1] ERROR in /Users/phucpnt/projects/wexond/src/main/dialogs/auth.ts(44,28):
[1] TS2339: Property 'appWindow' does not exist on type 'AuthDialog'.
[1] ERROR in /Users/phucpnt/projects/wexond/src/main/dialogs/credentials.ts(3,24):
[1] TS2307: Cannot find module '.'.
[1] ERROR in /Users/phucpnt/projects/wexond/src/main/dialogs/credentials.ts(21,28):
[1] TS2339: Property 'appWindow' does not exist on type 'CredentialsDialog'.
[1] ERROR in /Users/phucpnt/projects/wexond/src/main/dialogs/form-fill.ts(2,10):
[1] TS2305: Module '"../../../../../../../Users/phucpnt/projects/wexond/src/main/dialogs/dialog"' has no exported member 'Dialog'.
[1] Version: typescript 3.8.3
[1] Time: 57517 ms
[2] ERROR in /Users/phucpnt/projects/wexond/src/main/application.ts(66,40):
[2] TS2339: Property 'dialogs' does not exist on type 'AppWindow'.
[2] ERROR in /Users/phucpnt/projects/wexond/src/main/dialogs/auth.ts(8,24):
[2] TS2307: Cannot find module '.'.
[2] ERROR in /Users/phucpnt/projects/wexond/src/main/dialogs/auth.ts(30,12):
[2] TS2339: Property 'show' does not exist on type 'AuthDialog'.
[2] ERROR in /Users/phucpnt/projects/wexond/src/main/dialogs/auth.ts(31,12):
[2] TS2339: Property 'tabIds' does not exist on type 'AuthDialog'.
[2] ERROR in /Users/phucpnt/projects/wexond/src/main/dialogs/auth.ts(33,12):
[2] TS2339: Property 'send' does not exist on type 'AuthDialog'.
[2] ERROR in /Users/phucpnt/projects/wexond/src/main/dialogs/auth.ts(35,48):
[2] TS2339: Property 'appWindow' does not exist on type 'AuthDialog'.
[2] ERROR in /Users/phucpnt/projects/wexond/src/main/dialogs/auth.ts(36,14):
[2] TS2339: Property 'tabIds' does not exist on type 'AuthDialog'.
[2] ERROR in /Users/phucpnt/projects/wexond/src/main/dialogs/auth.ts(36,28):
[2] TS2339: Property 'tabIds' does not exist on type 'AuthDialog'.
[2] ERROR in /Users/phucpnt/projects/wexond/src/main/dialogs/auth.ts(36,43):
[2] TS7006: Parameter 'x' implicitly has an 'any' type.
[2] ERROR in /Users/phucpnt/projects/wexond/src/main/dialogs/auth.ts(37,14):
[2] TS2339: Property 'hide' does not exist on type 'AuthDialog'.
[2] ERROR in /Users/phucpnt/projects/wexond/src/main/dialogs/auth.ts(44,28):
[2] TS2339: Property 'appWindow' does not exist on type 'AuthDialog'.
[2] ERROR in /Users/phucpnt/projects/wexond/src/main/dialogs/credentials.ts(3,24):
[2] TS2307: Cannot find module '.'.
[2] ERROR in /Users/phucpnt/projects/wexond/src/main/dialogs/credentials.ts(21,28):
[2] TS2339: Property 'appWindow' does not exist on type 'CredentialsDialog'.
[2] ERROR in /Users/phucpnt/projects/wexond/src/main/dialogs/form-fill.ts(2,10):
[2] TS2305: Module '"../../../../../../../Users/phucpnt/projects/wexond/src/main/dialogs/dialog"' has no exported member 'Dialog'.
[2] Version: typescript 3.8.3
[2] Time: 61804 ms
[0] ERROR in /Users/phucpnt/projects/wexond/src/main/application.ts(66,40):
[0] TS2339: Property 'dialogs' does not exist on type 'AppWindow'.
[0] ERROR in /Users/phucpnt/projects/wexond/src/main/dialogs/auth.ts(8,24):
[0] TS2307: Cannot find module '.'.
[0] ERROR in /Users/phucpnt/projects/wexond/src/main/dialogs/auth.ts(30,12):
[0] TS2339: Property 'show' does not exist on type 'AuthDialog'.
[0] ERROR in /Users/phucpnt/projects/wexond/src/main/dialogs/auth.ts(31,12):
[0] TS2339: Property 'tabIds' does not exist on type 'AuthDialog'.
[0] ERROR in /Users/phucpnt/projects/wexond/src/main/dialogs/auth.ts(33,12):
[0] TS2339: Property 'send' does not exist on type 'AuthDialog'.
[0] ERROR in /Users/phucpnt/projects/wexond/src/main/dialogs/auth.ts(35,48):
[0] TS2339: Property 'appWindow' does not exist on type 'AuthDialog'.
[0] ERROR in /Users/phucpnt/projects/wexond/src/main/dialogs/auth.ts(36,14):
[0] TS2339: Property 'tabIds' does not exist on type 'AuthDialog'.
[0] ERROR in /Users/phucpnt/projects/wexond/src/main/dialogs/auth.ts(36,28):
[0] TS2339: Property 'tabIds' does not exist on type 'AuthDialog'.
[0] ERROR in /Users/phucpnt/projects/wexond/src/main/dialogs/auth.ts(36,43):
[0] TS7006: Parameter 'x' implicitly has an 'any' type.
[0] ERROR in /Users/phucpnt/projects/wexond/src/main/dialogs/auth.ts(37,14):
[0] TS2339: Property 'hide' does not exist on type 'AuthDialog'.
[0] ERROR in /Users/phucpnt/projects/wexond/src/main/dialogs/auth.ts(44,28):
[0] TS2339: Property 'appWindow' does not exist on type 'AuthDialog'.
[0] ERROR in /Users/phucpnt/projects/wexond/src/main/dialogs/credentials.ts(3,24):
[0] TS2307: Cannot find module '.'.
[0] ERROR in /Users/phucpnt/projects/wexond/src/main/dialogs/credentials.ts(21,28):
[0] TS2339: Property 'appWindow' does not exist on type 'CredentialsDialog'.
[0] ERROR in /Users/phucpnt/projects/wexond/src/main/dialogs/form-fill.ts(2,10):
```

I hope this help. I running mac 10.14.6

**Comment by sentialx** [comment]
@phucpnt Yeah, but what did you do to get the `TypeError: Object has been destroyed`?

**Comment by phucpnt** [comment]
@sentialx When running dev, I closed the browser before the exit the script.
